version: 3

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all

  cache:
    desc: Cache dependencies
    silent: true
    cmds:
      - go mod tidy

  start:
    desc: Start service
    deps:
      - cache
    silent: true
    cmds:
      # - sudo lsof -t -i tcp:8000 | xargs kill -9
      - go run .
    